name: mlops-ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.14' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
        
      - name: Run data preprocessing
        run: |
          python src/data/run_processing.py \
          --input data/raw/house_data.csv \
          --output data/processed/cleaned_house_data.csv


      - name: Do Feature Engineering
        run: |
          python src/features/engineer.py \
          --input data/processed/cleaned_house_data.csv \
          --output data/processed/featured_house_data.csv \
          --preprocessor models/trained/preprocessor.pkl
      
      - name: Start MLflow container
        run: |
          docker run -d --name mlflow \
            -p 5555:5000 \
            ghcr.io/mlflow/mlflow:latest \
            mlflow server --host 0.0.0.0 --backend-store-uri sqlite:///mlflow.db --default-artifact-root /tmp/mlruns
          sleep 15

      - name: Check MLflow health
        run: curl http://localhost:5555

      - name: Run Model Training
        run: |
          python src/models/train_model.py \
          --config configs/model_config.yaml \
          --data data/processed/featured_house_data.csv \
          --models-dir models \
          --mlflow-tracking-uri http://localhost:5555
      
      - name: Stop and remove MLflow container
        if: always()  # ensures cleanup even if previous step fails
        run: |
          docker stop mlflow || true
          docker rm mlflow || true
